version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing HTML Validator...
      - npm install -g htmlhint

  build:
    commands:
      - echo Running HTML Validation...
      - htmlhint *.html
      - echo HTML Validation successfull...

artifacts:
  files:
    - '**/*'
